spring.application.name=SoundCloudUsingSpringBoot

# Allowing Spring Boot to load .env file :D
spring.config.import=optional:file:.env[.properties]


# Database 
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Mail
# Gmail SMTP configuration used to send application emails.
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}

# SMTP account used for authentication and as the default sender.
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

# Enable SMTP authentication.
spring.mail.properties.mail.smtp.auth=true

# Encrypt the SMTP connection using STARTTLS.
spring.mail.properties.mail.smtp.starttls.enable=true

# SMTP connection and I/O timeouts (milliseconds).
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



# JWT secret key & expiration time
# - Generate a strong secret key for JWT.
#   You can use a secure password generator or generate one
# - from the Linux terminal. The following command generates
#   32 random bytes encoded as Base64 text:
#
#   openssl rand -base64 32
#
# Suitable for HS256 (256-bit secret key).
#  (SignatureAlgorithm.HS256 {256-bit (32 bytes)})
jwt.secret-key=${JWT_SECRET_KEY}

# Access token lifetime in milliseconds (1 hour).
jwt.expiration-time-ms=3600000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Development
    # Print every SQL query executed to the console.
spring.jpa.show-sql=true  
    # Makes SQL readable.
spring.jpa.properties.hibernate.format_sql=true

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

# Server
server.port=8080


