package com.soundcloud.SoundCloudUsingSpringBoot.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

import com.soundcloud.SoundCloudUsingSpringBoot.security.JwtAuthenticationFilter;

import lombok.RequiredArgsConstructor;

/**
 * Configures Spring Security for the application.
 *
 * Defines:
 * - authentication rules
 * - authorization rules
 * - session management
 * - security filters
 * - security-related beans
 */
@Configuration
@EnableWebSecurity
@RequiredArgsConstructor
public class SecurityConfig {

    /**
     * Custom JWT authentication filter responsible for
     * authenticating incoming requests using JWT.
     */
    private final JwtAuthenticationFilter jwtAuthenticationFilter;

    /**
     * Configures the application's HTTP security.
     *
     * Defines:
     * - stateless session management
     * - CSRF configuration
     * - authorization rules
     * - JWT authentication filter
     *
     * @param httpSecurity Spring Security's HTTP security builder
     * @return the configured SecurityFilterChain
     * @throws Exception if security configuration fails
     */
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {


        return httpSecurity
                // Configure Spring Security to use STATELESS authentication.
                // This means No HTTP session will be created or used to store authentication.
                .sessionManagement(
                        sessionConfig -> sessionConfig.sessionCreationPolicy(SessionCreationPolicy.STATELESS))

                // Disable CSRF protection since authentication is performed
                // using JWTs instead of session cookies.
                //
                // Rule:
                // JWT + Authorization header -> Disable CSRF
                // Session + Cookies          -> Enable CSRF
                .csrf(csrfConfig -> csrfConfig.disable())

                // Configure endpoints authorization rules.
                .authorizeHttpRequests(
                        authorizationConfig -> authorizationConfig
                                // Allow anyone to access authentication endpoints ( /auth/** ).
                                .requestMatchers("/auth/**").permitAll()
                                // Require authentication for all other endpoints.
                                .anyRequest().authenticated())

                // Execute the JWT authentication filter before Spring's
                // UsernamePasswordAuthenticationFilter so authenticated users
                // are available to the remaining security filters.
                .addFilterBefore(jwtAuthenticationFilter,
                        UsernamePasswordAuthenticationFilter.class)

                // Build and return the configured SecurityFilterChain.
                .build();

    }

    /**
     * Creates the PasswordEncoder used to hash and verify user passwords.
     *
     * BCrypt is chosen because it is specifically designed for password
     * hashing, incorporating a random salt and a configurable work factor
     * to resist brute-force attacks.
     * 
     * BCrypt hash contains:
     * - Algorithms
     * - Cost factor
     * - Salt (random value generated by BCrypt)
     * - Hash
     * 
     * @return the application's PasswordEncoder implementation
     */
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    /**
     * Exposes Spring Security's configured AuthenticationManager as a bean.
     *
     * Spring automatically configures the AuthenticationManager using
     * the application's UserDetailsService and PasswordEncoder beans.
     *
     * This AuthenticationManager will later be used during the login
     * process to authenticate user credentials.
     *
     * @param authenticationConfiguration Spring Security authentication configuration
     * @return the configured AuthenticationManager
     * @throws Exception if the AuthenticationManager cannot be created
     */
    @Bean
    public AuthenticationManager authenticationManager(AuthenticationConfiguration authenticationConfiguration)
            throws Exception {

        // Return the AuthenticationManager already configured by Spring.
        return authenticationConfiguration.getAuthenticationManager();
    }

}
